### ISSUE TITLE
adding indexed fields to all data calls

### ISSUE THREAD

**Issue by denislepage** [BirdStudiesCanada/NatureCountsAPI#2]
The so called "indexed fields" in bmde_data should be accessible through the API. I would prefer not to add them to the formal existing "BMDE standards" stored in lk_bmde_fields and lk_bmde_versions. I think the indexed fields (there are 28 of them now) should always be included in the response, regardless of the bmde version being asked. As Steffi rightly pointed out, this presents some challenges as we have 2 sets of fields often (but not always) containing the same things, and I don't like that we're providing data with field names that are not in accordance to our own standards.

I have added a new table that contains the list of 28 indexed fields (lk_bmde_fields_indexed). That list can also probably be loaded at servlet initialisation and appended to the list of returned fields for all data calls.

**Comment by denislepage** [comment]
Actually, I have shortened the list of indexed fields to be included in the API responses to 20. Not all of them were relevant.

**Comment by pmorrill** [comment]
The list of indexed fields will be part of all data queries, after the next deployment.
