### ISSUE TITLE
Permissions for list_permissions vs. get_data

### ISSUE THREAD

**Issue by pmorrill** [BirdStudiesCanada/NatureCountsAPI#20]
S. has been granted 'READ' access to all collections with akn_level 3 or greater, via the api_user_roles table. D. updated the basic 'list_permission' query so that her collection permission list reflects the record in api_user_roles.

However, when she queries for actual data, her collection access is determined by a call to prSelectCollectionsPermissions. I do no think that this proc has been updated to reflect the api_user_roles mechanism. (As reported earlier, I cannot see the proc code). It does not seem to return the accurate user_status for the case of someone granted access via the api_user_roles table.

I can work around this, but is it possible to use that proc to leverage the api_user_roles rules?

**Comment by steffilazerte** [comment]
Any updates on this? Another example is for Danielle: She can access BBS via `list_permissions`, but not with `get_data`

**Comment by pmorrill** [comment]
I have just checked in a new version that should work for you. I am not sure if Denis plans to adjust the proc (as I mention above), so I added a work-around for the time being. Denis - can you re-build bsc-base to get this in place for testing?

**Comment by denislepage** [comment]
I have modified the proc [prSelectCollectionsPermissions] to incorporate user roles. For those users with READ permissions across all projects (only 3 so far), it now returns the maximum between the value 7 (regular user) and the value assigned explicitly for that collection and user.

Let me know if that works.

**Comment by steffilazerte** [comment]
Works fine on my end

**Comment by denislepage** [comment]
I have pushed the changes to the sandbox server just now as well, but that may be overkill now.

**Comment by pmorrill** [comment]
Steffi - you need to retest this after the next deploy. Above, you were testing my work-around, not Denis' fix to the database proc. However, I have reverted the code to using his (improved) proc and it should now behave.

**Comment by steffilazerte** [comment]
Still works after the redeploy, thanks!
