### ISSUE TITLE
metadata/collections has typo?

### ISSUE THREAD

**Issue by steffilazerte** [BirdStudiesCanada/NatureCountsAPI#6]
When I request the collections metadata, the first field is bmd**r**_code, should this be bmd**e**_code?

**Comment by pmorrill** [comment]
bmdr_code is a field directly out of the database (one of the indexed fields). Denis will have to explain the meaning.....

**Comment by denislepage** [comment]
No, bmdr is correct.

= bird monitoring data registry.

several collections can refer to the same bmdr code.

**Comment by steffilazerte** [comment]
Good to know!
So what does BMDE stand for?

**Comment by denislepage** [comment]
Bird Monitoring Data Exchange.
