### ISSUE TITLE
version vs bmdeVersion

### ISSUE THREAD

**Issue by pmorrill** [BirdStudiesCanada/NatureCountsAPI#7]
We should resolve a potential confusion that arises by use of 'version' in two places. We currently have 'version' attached to the 'meta-data version' concept - returned at the time of authentication, or in response to the api/api_version query.

We are also using version as a filter attribute when requesting data. 

Does anyone object if I revert the latter back to the original name, which was 'bmdeVersion', to avoid any confusion.

**Comment by steffilazerte** [comment]
That's fine by me

I've been struggling a bit with how to keep things simple in the R code. Right now I use `metadata_v_local` and `metadata_v_remote` for functions which return the local and remote metadata versions respectively.

For the bmdeVersion/fields, I use just the argument `fields` in the data download function which can take either fields, a version, or a version shorthand. Inside the function, R figures out what values of `fields` and `bmdeVersion` to send to the API, based on those options. So for me, `bmdeVersion` is an internal thing.

**Comment by steffilazerte** [comment]
@denislepage FYI, I've changed this to two separate arguments in the R code, to keep things simpler.
